require("dotenv").config();

export default {
  CHEFS_FISCAL_YEAR_REPORTING_DATES_FORM_ID:
    process.env.CHEFS_FISCAL_YEAR_REPORTING_DATES_FORM_ID,
  CHEFS_FISCAL_YEAR_REPORTING_DATES_API_KEY:
    process.env.CHEFS_FISCAL_YEAR_REPORTING_DATES_API_KEY,
  CHEFS_PCN_BUDGET_FORM_ID: process.env.CHEFS_PCN_BUDGET_FORM_ID,
  CHEFS_PCN_BUDGET_API_KEY: process.env.CHEFS_PCN_BUDGET_API_KEY,
  CHEFS_CHC_BUDGET_FORM_ID: process.env.CHEFS_CHC_BUDGET_FORM_ID,
  CHEFS_CHC_BUDGET_API_KEY: process.env.CHEFS_CHC_BUDGET_API_KEY,
  CHEFS_UPCC_BUDGET_FORM_ID: process.env.CHEFS_UPCC_BUDGET_FORM_ID,
  CHEFS_UPCC_BUDGET_API_KEY: process.env.CHEFS_UPCC_BUDGET_API_KEY,
  CHEFS_NPPCC_BUDGET_FORM_ID: process.env.CHEFS_NPPCC_BUDGET_FORM_ID,
  CHEFS_NPPCC_BUDGET_API_KEY: process.env.CHEFS_NPPCC_BUDGET_API_KEY,
  CHEFS_PCN_FINANCIAL_FORM_ID: process.env.CHEFS_PCN_FINANCIAL_FORM_ID,
  CHEFS_PCN_FINANCIAL_API_KEY: process.env.CHEFS_PCN_FINANCIAL_API_KEY,
  CHEFS_CHC_FINANCIAL_FORM_ID: process.env.CHEFS_CHC_FINANCIAL_FORM_ID,
  CHEFS_CHC_FINANCIAL_API_KEY: process.env.CHEFS_CHC_FINANCIAL_API_KEY,
  CHEFS_UPCC_FINANCIAL_FORM_ID: process.env.CHEFS_UPCC_FINANCIAL_FORM_ID,
  CHEFS_UPCC_FINANCIAL_API_KEY: process.env.CHEFS_UPCC_FINANCIAL_API_KEY,
  CHEFS_NPPCC_FINANCIAL_FORM_ID: process.env.CHEFS_NPPCC_FINANCIAL_FORM_ID,
  CHEFS_NPPCC_FINANCIAL_API_KEY: process.env.CHEFS_NPPCC_FINANCIAL_API_KEY,
  CHEFS_API_URL: process.env.CHEFS_API_URL,
  PORT: process.env.PORT,
  ENVIRONMENT: process.env.ENVIRONMENT,
  TEMPLATE_ROUTE: process.env.TEMPLATE_ROUTE,
};
