export default {
  CHC: {
    sheetId: 1,
    fiscalYear: "B",
    periodReported: "C",
    healthAuthority: "D",
    communityName: "E",
    chcName: "F",
    financialData: "G",
    expenseCategory: "H",
    expenseSubCategory: "I",
    expenseItem: "J",
    expenseItemSubType: "K",
    p1: "L",
    p2: "M",
    p3: "N",
    p4: "O",
    p5: "P",
    p6: "Q",
    p7: "R",
    p8: "S",
    p9: "T",
    p10: "U",
    p11: "V",
    p12: "W",
    p13: "X",
    ftesHiredToDate: "Y",
    fyExpenseForecast: "Z",
    ytdExpenseVarianceNote: "AA",
    fyExpenseVarianceNote: "AB",
    additionalNotes: "AC",
  },
  PCN: 2,
  UPCC: 3,
};
